# Site settings
title: "Best Practices, Content Strategy and Technology for B2B Blogs"
email: ""
description: "Regular insight about content strategy, Markdown and writing technology to help B2B content teams generate and convert leads."
baseurl: "/beegit.github.io"


# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
permalink: pretty

gems:
  - jekyll-redirect-from
  - jekyll-redirect-to
