# Site settings
title: "Thoughts on content strategy, markdown and writing technology"
email: "mike@beegit.com"
description: "Regular insight about content strategy, markdown and writing technology to help content teams increase productivity."
baseurl: ""
url: "http://blog.beegit.com"

# Build settings
markdown: kramdown
permalink: pretty

