# Site settings
title: Beegit Buzz
email: mike@beegit.com
description: "Beegit buzz shares regular insight about technology and techniques in content development to help make it easier for people to create content together."
baseurl: ""
url: "http://blog.beegit.com"

# Build settings
markdown: kramdown
permalink: pretty
