# Site settings
title: Contentable - Beegit's blog on agile content, content strategy & writing technology
email: mike@beegit.com
description: "Contentable shares regular insight about technology and techniques in content development to help make it easier for people to create content together."
baseurl: ""
url: "http://blog.beegit.com"

# Build settings
markdown: kramdown
permalink: pretty

# gems:
#  - jekyll-redirect-from
